### ISSUE TITLE
[ 1.20.1 1.0.0 ] [Bug] Summoning the dice will cause a crash

### ISSUE THREAD

**Issue by tankplanelaserkoala** [MrUnknown404/Dice#4] opened 2024-03-03 10:09 UTC
**Describe the bug**
Summoning dice with the /summon command will cause a crash

**To Reproduce**
1. Type /summon dice:dice_entity
2. Crashes happen.

**Expected behavior**
I think it's summoning 1 white dice

**Screenshots**

**Additional context**
forge version : 47.2.20

**Comment by SNWCreations** [comment] 2024-03-31 01:30
This is caused by summoning the entity without the data required by the entity. This mod uses RGB color values to indicates that how the entity will be rendered, and also "type" and "rolled" for render.
However, if you use /summon without specifying any data, type and rolled will have default "0" value, 0 is not allowed by the mod, so it will crash.

**Comment by SNWCreations** [comment] 2024-03-31 02:08
Fixed by #5, the fix is also included in my fabric port of this mod.

**Comment by MrUnknown404** [comment] 2024-04-02 20:31
Thank you for investigating for me. Ngl, I totally forgot about this issue. I'll post a version with your fix later today

**Closed as completed** 2024-04-02 21:17 UTC
Labels: Status: Fixed, Type: Bug
